# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3556afbd29d303efddb94237c2d43d07bb38212aea288dd993e62fef7ad47a751e45edf8fbf0f683fe64178e90eb20a2f6176a2d87103a99317f624eefe612f8

test:
  secret_key_base: 5f8fb148f89471f399dd75f74bf0dc738a2151cf5e9c16983f743e4d381bae3f475133316d78771a9d018379e025b6955fbefa3ec8db71042c9c280e489cb7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
